#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HubsApp.Resource", IsApplication=true)]

namespace HubsApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Utils.Resource.String.ApplicationName = global::HubsApp.Resource.String.ApplicationName;
			global::Utils.Resource.String.Hello = global::HubsApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dot = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int home_logo_top = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_03 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_03_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_en = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_gcoding = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_geo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_marka = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_markb = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_markc = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_markd = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_marke = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_markf = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_markg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_markh = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_marki = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_markj = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_st = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int infowindow_bg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int location = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int location_back = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int location_tips = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int map_location = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int map_location_red = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int monoandroidsplash = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int next_ = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int next_down_ = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int popup = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int popup_down = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int popup_left = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int popup_middle = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int popup_right = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int popup_side = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int pre_ = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pre_down_ = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int HotelListView = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int bmapView = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int itemText = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int itemTitle = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int myListItem = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int txtHotelCoordinate = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int txtHotelName = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Details = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int my_listItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Lat = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Lon = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
